/**
 * Conversation titles for the chat sidebar, derived from the user's own first
 * message rather than generated by a model. Mastra Memory can auto title a
 * thread with an extra LLM call; on free tier quotas that is one more request
 * competing with the actual answer, and a truncated first line is what the user
 * would recognise anyway (docs/DECISIONS.md D-49).
 */

export const DEFAULT_CONVERSATION_TITLE = 'New chat';

const MAX_TITLE_LENGTH = 60;

/** Collapses whitespace and strips leading markdown markers, then cuts at a word boundary. */
export function deriveConversationTitle(text: string, maxLength: number = MAX_TITLE_LENGTH): string {
  const firstLine =
    text
      .split(/\r?\n/)
      .map((line) => line.replace(/^\s*(#{1,6}\s+|[-*>]\s+|\d+\.\s+)/, '').trim())
      .find((line) => line.length > 0) ?? '';
  const clean = firstLine.replace(/[*_`]+/g, '').replace(/\s+/g, ' ').trim();
  if (clean.length === 0) return DEFAULT_CONVERSATION_TITLE;
  if (clean.length <= maxLength) return clean;

  const cut = clean.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(' ');
  // Only back off to a word boundary when it keeps most of the text; a single long
  // token (a URL, a file name) is better cut mid-word than reduced to nothing.
  const base = lastSpace > maxLength * 0.6 ? cut.slice(0, lastSpace) : cut;
  return `${base.replace(/[\s.,;:!?-]+$/, '')}…`;
}

/** True for a title nobody chose: empty, our own default, or Mastra's "New Thread <date>" placeholder. */
export function isPlaceholderTitle(title: string | null | undefined): boolean {
  if (!title || title.trim().length === 0) return true;
  const t = title.trim();
  return t === DEFAULT_CONVERSATION_TITLE || /^new thread\b/i.test(t);
}

type TextBearingMessage = {
  role?: string;
  parts?: readonly { type: string; text?: string }[];
  content?: unknown;
};

/** The plain text of a message, from AI SDK UI parts or a plain string content. */
export function messageText(message: TextBearingMessage): string {
  if (Array.isArray(message.parts)) {
    return message.parts
      .filter((p) => p.type === 'text' && typeof p.text === 'string')
      .map((p) => p.text as string)
      .join('\n');
  }
  return typeof message.content === 'string' ? message.content : '';
}

/** The text of the first user message in a list, or '' when there is none. */
export function firstUserText(messages: readonly TextBearingMessage[]): string {
  const first = messages.find((m) => m.role === 'user' && messageText(m).trim().length > 0);
  return first ? messageText(first) : '';
}
