export { closeSession, createSession, disableExternalAccess, registerFile, summarizeTable } from './session';
export type { DuckDBSession, RegisterFileOptions } from './session';
export { registerRows } from './registerRows';
export type { RowTable } from './registerRows';
export { sqlCodeText, validateSql } from './validateSql';
export { lintRatioAverages, AVERAGE_OF_PER_ROW } from './ratioLint';
export { resolveEvidenceValue } from './evidenceValue';
export type { CellPick, ResolvedValue } from './evidenceValue';
export { query } from './query';
export type { QueryOptions, QueryResult } from './query';
export { describe } from './describe';
export type { ColumnProfile, TableProfile } from './describe';
export { detectQualityIssues } from './qualityWarnings';
export { computeStats, twoProportionZTest, welchTTest } from './computeStats';
export type { SmallSampleRow, StatsOp, StatsResult, TwoProportionZTest } from './computeStats';
export { normalTwoSidedP, studentTTwoSidedP } from './distributions';
export { toJsonSafeValue, rowToJsonSafe } from './values';
export type { QueryValue } from './values';
export { referencedTables, scopeViolations } from './referencedTables';
export type { ReferencedTables, TableReference, TableScope } from './referencedTables';
