import React from "react";
import { AbsoluteFill, Audio, Series, staticFile } from "remotion";
import { STAGE } from "./theme";
import { Hook, HOOK_DURATION } from "./scenes/Hook";
import { Brand, BRAND_DURATION } from "./scenes/Brand";
import { Upload, UPLOAD_DURATION } from "./scenes/Upload";
import { Analysis, ANALYSIS_DURATION } from "./scenes/Analysis";
import { Conflict, CONFLICT_DURATION } from "./scenes/Conflict";
import { Agents, AGENTS_DURATION } from "./scenes/Agents";
import { Artifacts, ARTIFACTS_DURATION } from "./scenes/Artifacts";
import { Features, FEATURES_DURATION } from "./scenes/Features";
import { Outro, OUTRO_DURATION } from "./scenes/Outro";

export const SCENES = [
  { id: "hook", Component: Hook, duration: HOOK_DURATION },
  { id: "brand", Component: Brand, duration: BRAND_DURATION },
  { id: "upload", Component: Upload, duration: UPLOAD_DURATION },
  { id: "analysis", Component: Analysis, duration: ANALYSIS_DURATION },
  { id: "conflict", Component: Conflict, duration: CONFLICT_DURATION },
  { id: "agents", Component: Agents, duration: AGENTS_DURATION },
  { id: "artifacts", Component: Artifacts, duration: ARTIFACTS_DURATION },
  { id: "features", Component: Features, duration: FEATURES_DURATION },
  { id: "outro", Component: Outro, duration: OUTRO_DURATION },
] as const;

export const DEMO_DURATION = SCENES.reduce((n, s) => n + s.duration, 0);

export const Demo: React.FC = () => (
  <AbsoluteFill style={{ background: STAGE.bg }}>
    {/* Generated by scripts/make-soundtrack.ts (npm run soundtrack), timed from src/timeline.ts. */}
    <Audio src={staticFile("soundtrack.wav")} />
    <Series>
      {SCENES.map(({ id, Component, duration }) => (
        <Series.Sequence key={id} durationInFrames={duration} name={id}>
          <Component />
        </Series.Sequence>
      ))}
    </Series>
  </AbsoluteFill>
);
